### ISSUE TITLE
 He is not executing the rcon command correctly

### ISSUE THREAD

**Issue by bibi-blocksberg** [dichternebel/csgo-rcon-bot#47]
I send 

!csgo rcon sm_addvip "STEAM_0:0:168081715"2"Rtcxxx"

And   He is not executing the rcon command correctly

CS:GO Server RCON
Added as VIP for 0 Month
L 12/11/2021 - 14:49:14: rcon from "179.61.xx.xx:60924": command "sm_addvip STEAM_0:0:1680817152Rtcxxx"

"sm_addvip "STEAM_0:0:168081715"2"Rtcxxx"
"sm_addvip STEAM_0:0:1680817152Rtcxxx"

he doesn't use the quotation marks

can u help me please

**Comment by dichternebel** [comment]
Is this `sm_addvip` some extension or plugin to your CS:GO server? I don't know that... besides that I would say you have to add spaces when sending the command like `sm_addvip "STEAM_0:0:0000000" 2 "blabla"` ... or just leave the quotes?
I'm only guessing here.
Is it working when using the rcon-cli directly? How do you use it there?
Imho you should add a custom bot command for that purpose instead of using the generic rcon command.

**Comment by bibi-blocksberg** [comment]
https://forums.alliedmods.net/showthread.php?t=292183
this is the plugin 

and this command works on console 

Spaces are useless, I've tried that

and i don't know how i can add a custom command to your bot i don't know how to program it


thank you

**Comment by bibi-blocksberg** [comment]
it does not recognize the "" the differences for the steamd id, duration and name

**Comment by dichternebel** [comment]
Without giving spaces between each parameter it can't work from the rcon-cli. The link you posted also gives examples with spaces. The console inside CS:GO has nothing to do with that.

Could you try this command that is escaping the quotes and sends it to the bot:
`!csgo rcon "sm_addvip \"STEAM_0:0:168081715\" 2 \"Rtcxxx\""`
You might ask at the rcon-cli project or tVip project  for help on how to pass multiple parameters at once since the bot is only passing a command directly to the rcon-cli at the end of the day.

# rcon-cli
https://github.com/itzg/rcon-cli

# tVip
https://github.com/Totenfluch/tVip

**Comment by bibi-blocksberg** [comment]
yes this command works  =)
